name: arch_ledger
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0
environment:
  sdk: '>=3.0.3 <4.0.0'
dependencies:
  fast_log: ^1.0.5
  hive_flutter: ^1.1.0
  precision_stopwatch: ^1.0.2
  json_serializable: ^6.7.0
  json_annotation: ^4.8.1
  build_runner: ^2.4.5
  toxic: ^1.0.3
  rxdart: ^0.27.7
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  intl: ^0.18.1
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
flutter:
